### PR TITLE
webgui

### PR DESCRIPTION
**Pull request by yuhanxu01**

### CODE REVIEW

**Comment by nitinmukesh** [comment]
Got this error

```
(anitalker) C:\tut\AniTalker>python webgui.py
Traceback (most recent call last):
  File "C:\tut\AniTalker\webgui.py", line 18, in <module>
    from LIA_Model import LIA_Model
ModuleNotFoundError: No module named 'LIA_Model'
```

is it because LIA_Model is inside code folder?

**Comment by nitinmukesh** [comment]
Tested working on Windows.

In requirements
gradio to be added

image

**Comment by liutaocode** [comment]
Thank you for your submission. Some areas still need improvement, and the model is loading each time. I'll approve it for now, and I will fix this issue later.

**Comment by nitinmukesh** [comment]
@liutaocode 

The webui is not merged. Please can you review
https://github.com/yuhanxu01/AniTalker/blob/af1ae37533236d97853683720d633152bb1534ba/code/webgui.py

**Pull request merged**
